kind: pipeline
type: docker
name: default

steps:
- name: test
  image: loongcr.lcpu.dev/lcpu/archlinux
  commands:
  - cd glibc
  - pacman -S --noconfirm --needed gd git python sudo fakeroot base-devel
  - echo 'MAKEFLAGS="-j4"' | sudo tee -a /etc/makepkg.conf
  - useradd builduser -m
  - chown -R builduser /drone/src/
  - sudo -u builduser bash -c 'cd $(pwd) && makepkg -CL --nocheck'
