kind: pipeline
type: docker
name: default

steps:
- name: test
  image: loongcr.lcpu.dev/lcpu/archlinux
  commands:
  - cd glibc
  - pacman -S --noconfirm --needed gd git python
  - makepkg -CL --nocheck
